insert into PMS_USER (ID, USER_ACCOUNT, USER_NAME, USER_PASSWORD, USER_SEX, USER_EMAIL, USER_LANGUAGE, USER_PHONE, USER_ADDRESS, USER_PLACE, USER_FACE, USER_IDCARD, USER_PIC, DEPT_ID, USER_POSITION, USER_AGE, USER_BIRTH, ENTRY_DATE, DIPLOMA_SCHOOL, DIPLOMA_DATE, USER_RECORD, USER_MOBILE, USER_COUNT, USER_REMARK, USER_FLAG, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, USER_NATURE)
values (1, 'admin', '管理员', '16D7A4FCA7442DDA3AD93C9A726597E4', '1', null, '0', null, null, null, '0', '430502199511236047', '/assets/template/userIcon/347D36B2AB5B41F7881CD7F1519B2678.jpg', 26, '0', '20', to_date('06-02-2018', 'dd-mm-yyyy'), to_date('06-02-2018', 'dd-mm-yyyy'), null, to_date('06-02-2018', 'dd-mm-yyyy'), null, null, null, null, '0', 'admin', to_date('06-02-2018 10:33:45', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('03-04-2018 18:03:25', 'dd-mm-yyyy hh24:mi:ss'), '1');
commit;
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (1, 'R001', null, '0', '系统管理', 'systemManagement', null, 6, '0', 'icon-settings');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (2, 'R002', null, '0', '售前管理', 'preSaleManagement', null, 0, '0', 'icon-briefcase');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (3, 'R003', null, '0', '合同管理', 'contractManagement', null, 1, '0', 'icon-docs');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (4, 'R004', null, '0', '项目管理', 'projectManagement', null, 2, '0', 'icon-calendar');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (5, 'R005', null, '0', '任务管理', 'taskManagement', null, 3, '0', 'icon-star');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (6, 'R006', null, '0', '绩效管理', 'achieveManagement', null, 4, '0', 'icon-trophy');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (7, 'R007', null, '0', '运营分析', 'operationAnalysis', null, 5, '1', 'icon-bar-chart');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (8, 'R002_01', 'presalemanage/customManageMain', '1', '客户维护', 'customerManagement', 2, 0, '0', 'icon-users');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (9, 'R002_02', 'presalemanage/saleTrackMain', '1', '销售跟踪', 'salesTrack', 2, 1, '0', 'icon-cursor');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (10, 'R003_01', 'contractmanage/contractManageMain', '1', '合同维护', 'contractManage', 3, 0, '0', 'icon-book-open');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (11, 'R003_02', 'contractmanage/contractApprovalMain', '1', '合同审批', 'contractCheck', 3, 1, '0', 'icon-docs');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (12, 'R003_03', 'contractmanage/receiveNodeManageMain', '1', '收款节点管理', 'receiveNodeManage', 3, 2, '0', 'icon-drop');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (13, 'R003_04', 'contractmanage/contractExecuInfoMain', '1', '合同执行情况', 'contractCondition', 3, 3, '0', 'icon-hourglass');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (14, 'R004_01', 'projectManager/projectManagerMain', '1', '项目立项', 'projectSetup', 4, 0, '0', 'fa fa-file-o');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (15, 'R004_02', 'projectMonitorManager/projectMonitorManagerMain', '1', '项目监控', 'projectMonitor', 4, 2, '0', 'icon-cursor');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (16, 'R004_03', 'projectManagement/costManagementMain', '1', '单价管理', 'costManagement', 4, 3, '0', 'fa fa-rmb');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (17, 'R005_01', 'taskManager/taskAssignManagerMain', '1', '任务分派', 'taskAssignment', 5, 0, '0', 'fa fa-tags');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (18, 'R005_02', 'taskManager/myTaskManagerMain', '1', '我的任务', 'myTask', 5, 1, '0', 'fa fa-tasks');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (19, 'R006_01', 'performanceManager/performanceManagerMain', '1', '绩效档案', 'achieveFile', 6, 0, '0', 'fa fa-folder');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (20, 'R006_02', 'dailyReportManager/dailyReportManagerMain', '1', '日报管理', 'dailyReport', 6, 1, '0', 'fa fa-file-text-o');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (118, 'OPERATION0403', null, '2', '操作权限', '操作', 16, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (22, 'R006_03', 'monthReportManager/monthReportManagerMain', '1', '月报管理', 'monthReport', 6, 2, '0', 'fa fa-file-text');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (23, 'R007_01', 'operationAnalysis/projectBonus', '1', '项目利润分析', 'projectBonus', 7, 0, '1', 'fa fa-bar-chart');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (24, 'R007_02', 'operationAnalysis/proMonthReport', '1', '项目月报', 'proMonthReport', 7, 1, '1', 'fa fa-file-archive-o');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (25, 'R001_01', 'userManage/userManagerMain', '1', '用户管理', 'userManagement', 1, 0, '0', 'icon-user');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (26, 'R001_02', 'roleManager/roleManagerMain', '1', '角色管理', 'roleManagement', 1, 1, '0', 'fa fa-user-secret');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (27, 'R001_03', 'logerManager/logerOperateMain', '1', '操作日志', 'operateLog', 1, 2, '0', 'fa fa-files-o');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (28, 'R001_07', 'passManager/modifyPassInitMain', '1', '修改密码', 'modifyPassInit', 1, 6, '0', 'fa fa-wrench');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (30, 'R001_04', 'logerManager/logerSystemMain', '1', '系统日志', 'systemLog', 1, 3, '0', 'fa fa-file');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (31, 'R001_05', 'codeManager/codeManagerMain', '1', '基础信息维护', 'basisInfoMaintenance', 1, 4, '0', 'fa fa-cog');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (119, 'OPERATION0404', null, '2', '操作权限', '操作', 33, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (120, 'OPERATION0405', null, '2', '操作权限', '操作', 34, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (145, 'R004_0301', null, '2', '新增/编辑', '新增/编辑', 118, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (146, 'R004_0302', null, '2', '删除', '删除', 118, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (147, 'R004_0401', null, '2', '新增/编辑', '新增/编辑', 119, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (148, 'R004_0402', null, '2', '删除', '删除', 119, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (149, 'R004_0502', null, '2', '删除', '删除', 120, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (150, 'R004_0501', null, '2', '新增/编辑', '新增/编辑', 120, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (151, 'R004_0503', null, '2', '导出', '导出', 120, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (153, 'R004_0601', null, '2', '审批', '审批', 121, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (33, 'R004_04', 'projectManagement/workHoursManagerMain', '1', '工时统计', 'workHoursManagerMain', 4, 4, '0', 'fa fa-spinner');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (154, 'OPERATION0401', null, '2', '操作权限', '操作权限', 14, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (155, 'R004_0101', null, '2', '新增/编辑', '新增/编辑', 154, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (156, 'R004_0102', null, '2', '删除', '删除', 154, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (157, 'R004_0103', null, '2', '提交', '提交', 154, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (158, 'R004_0104', null, '2', '里程碑新增/编辑', '里程碑新增/编辑', 154, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (159, 'R004_0105', null, '2', '里程碑删除', '里程碑删除', 154, 4, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (160, 'R004_0106', null, '2', '交付物新增/编辑', '交付物新增/编辑', 154, 5, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (161, 'R004_0107', null, '2', '交付物删除', '交付物删除', 154, 6, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (162, 'OPERATION0402', null, '2', '操作权限', '操作权限', 15, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (163, 'R004_0201', null, '2', '监控项目', '监控项目', 162, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (164, 'R004_0202', null, '2', '里程碑编辑', '里程碑编辑', 162, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (165, 'R004_0203', null, '2', '里程碑调整新增/编辑', '里程碑调整新增/编辑', 162, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (166, 'R004_0204', null, '2', '交付物编辑', '交付物编辑', 162, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (34, 'R004_05', 'projectManagement/otherCostMain', '1', '其他成本', 'otherCostMain', 4, 5, '0', 'fa fa-dollar');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (121, 'R004_06', 'projectManager/projectCheckMain', '1', '项目审批', 'projectCheck', 4, 1, '0', 'fa fa-check-square-o');
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (128, 'R002_0101', null, '2', '新增/编辑客户', '新增/编辑客户', 122, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (129, 'R002_0102', null, '2', '删除客户', '删除客户', 122, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (130, 'R002_0103', null, '2', '新增/编辑联系人', '新增/编辑联系人', 122, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (131, 'R002_0104', null, '2', '删除联系人', '删除联系人', 122, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (132, 'R002_0201', null, '2', '新增/编辑销售项目', '新增/编辑销售项目', 123, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (133, 'R002_0202', null, '2', '删除销售项目', '删除销售项目', 123, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (134, 'R002_0203', null, '2', '新增/编辑销售活动', '新增/编辑销售活动', 123, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (135, 'R002_0204', null, '2', '删除销售活动', '删除销售活动', 123, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (136, 'R003_0101', null, '2', '新增/编辑', '新增/编辑', 124, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (137, 'R003_0102', null, '2', '删除', '删除', 124, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (138, 'R003_0103', null, '2', '提交合同', '提交合同', 124, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (139, 'R003_0201', null, '2', '合同审核', '合同审核', 125, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (140, 'R003_0301', null, '2', '新增/编辑', '新增/编辑', 126, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (141, 'R003_0302', null, '2', '删除', '删除', 126, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (142, 'R003_0401', null, '2', '合同跟踪', '合同跟踪', 127, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (143, 'R003_0402', null, '2', '新增/编辑跟踪信息', '新增/编辑跟踪信息', 127, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (144, 'R003_0403', null, '2', '删除跟踪信息', '删除跟踪信息', 127, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (63, 'R001_0101', null, '2', '新增/编辑', '新增/编辑', 84, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (74, 'R001_0502', null, '2', '启用/禁用', '启用/禁用', 86, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (64, 'R001_0102', null, '2', '角色分配', '角色分配', 84, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (65, 'R001_0103', null, '2', '重置密码', '重置密码', 84, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (66, 'R001_0104', null, '2', '启用/禁用', '启用/禁用', 84, 4, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (75, 'R001_0601', null, '2', '新增/编辑', '新增/编辑', 87, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (76, 'R001_0602', null, '2', '删除', '删除', 87, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (70, 'R001_0201', null, '2', '新增/编辑', '新增/编辑', 85, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (71, 'R001_0202', null, '2', '分配资源', '分配资源', 85, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (72, 'R001_0203', null, '2', '启用/禁用', '启用/禁用', 85, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (73, 'R001_0501', null, '2', '新增/编辑', '新增/编辑', 86, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (77, 'R006_0101', null, '2', '生成当月绩效', '生成当月绩效', 88, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (78, 'R006_0102', null, '2', '绩效管理', '绩效管理', 88, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (79, 'R006_0103', null, '2', '绩效评分', '绩效评分', 88, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (80, 'R006_0201', null, '2', '新增/编辑', '新增/编辑', 89, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (81, 'R006_0202', null, '2', '删除', '删除', 89, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (97, 'OPERATION0603', null, '2', '操作权限', '操作', 22, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (98, 'DATA0603', null, '2', '数据权限', '数据', 22, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (84, 'OPERATION0101', null, '2', '操作权限', '操作', 25, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (85, 'OPERATION0102', null, '2', '操作权限', '操作', 26, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (86, 'OPERATION0105', null, '2', '操作权限', '操作', 31, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (87, 'OPERATION0106', null, '2', '操作权限', '操作', 32, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (88, 'OPERATION0601', null, '2', '操作权限', '操作', 19, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (89, 'OPERATION0602', null, '2', '操作权限', '操作', 20, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (90, 'DATA0602', null, '2', '数据权限', '数据', 20, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (102, 'VIEW_01', null, '2', '查看个人', '查看个人', 98, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (94, 'VIEW_01', null, '2', '查看个人', '查看个人', 90, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (95, 'VIEW_02', null, '2', '查看部门', '查看部门', 90, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (96, 'VIEW_03', null, '2', '查看全部', '查看全部', 90, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (103, 'VIEW_02', null, '2', '查看部门', '查看部门', 98, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (104, 'VIEW_03', null, '2', '查看全部', '查看全部', 98, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (106, 'R006_0301', null, '2', '新增/编辑', '新增/编辑', 97, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (107, 'R006_0302', null, '2', '删除', '删除', 97, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (108, 'OPERATION0501', null, '2', '操作权限', '操作', 17, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (109, 'DATA0501', null, '2', '数据权限', '数据', 17, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (110, 'VIEW_01', null, '2', '查看个人', '查看个人', 109, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (111, 'VIEW_02', null, '2', '查看部门', '查看部门', 109, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (112, 'VIEW_03', null, '2', '查看全部', '查看全部', 109, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (113, 'R005_0101', null, '2', '新增/编辑', '新增/编辑', 108, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (114, 'R005_0102', null, '2', '删除', '删除', 108, 2, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (115, 'R005_0103', null, '2', '发送/退回', '发送/退回', 108, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (116, 'OPERATION0502', null, '2', '操作权限', '操作', 18, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (117, 'R005_0201', null, '2', '编辑', '编辑', 116, 1, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (152, 'R004_0403', null, '2', '导出', '导出', 119, 3, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (122, 'OPERATION0201', null, '2', '操作权限', '操作', 8, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (123, 'OPERATION0202', null, '2', '操作权限', '操作', 9, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (124, 'OPERATION0301', null, '2', '操作权限', '操作', 10, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (125, 'OPERATION0302', null, '2', '操作权限', '操作', 11, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (126, 'OPERATION0303', null, '2', '操作权限', '操作', 12, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (127, 'OPERATION0304', null, '2', '操作权限', '操作', 13, 0, '0', null);
insert into PMS_RESOURCE (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (32, 'R001_06', 'deptManager/deptManagerMain', '1', '组织架构维护', 'Organizational maintenance', 1, 5, '0', 'fa fa-object-group');
commit;



insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (1, 'RE001', '系统管理员', 'SYSTEM', '0', null, 'admin', to_date('06-02-2018 10:51:17', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('15-03-2018 18:09:47', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (2, 'RE007', '经理', 'The manager', '0', 'PM', null, to_date('02-03-2018 17:57:14', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('15-03-2018 16:36:02', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (3, 'RE006', '公司领导', 'The company leadership', '0', null, null, to_date('02-03-2018 17:57:35', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('15-03-2018 18:09:44', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (4, 'RE005', '研发负责人', 'Research and development head', '0', null, null, to_date('05-03-2018 09:51:11', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('15-03-2018 18:09:41', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (5, 'RE004', '实施负责人', 'Implementation of the head', '0', null, null, to_date('05-03-2018 09:55:55', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('15-03-2018 18:09:37', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (6, 'RE003', '商务人员', 'Business people', '0', null, null, to_date('05-03-2018 10:02:39', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('15-03-2018 18:09:24', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_ROLE (ID, ROLE_CODE, ROLE_CNAME, ROLE_ENAME, ROLE_FLAG, ROLE_DESC, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (7, 'RE002', '普通员工', 'Ordinary employees', '0', null, '1', to_date('08-03-2018 10:00:39', 'dd-mm-yyyy hh24:mi:ss'), '1', to_date('03-04-2018 15:03:12', 'dd-mm-yyyy hh24:mi:ss'));
commit;

INSERT INTO PMS_USERROLE (USER_ID, ROLE_ID) 
SELECT 1,ID FROM PMS_ROLE;

INSERT INTO PMS_ROLERESOURCE(ROLE_ID,RESOURCE_ID)
SELECT 1,ID FROM PMS_RESOURCE;

commit;

insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (11, '开发工程师', '开发工程师', '0', 'position', '0', '岗位', 1, to_date('05-03-2018 17:01:45', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('05-03-2018 17:01:45', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (12, '实施工程师', '实施工程师', '1', 'position', '0', '岗位', 1, to_date('05-03-2018 17:01:45', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('05-03-2018 17:01:45', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (41, 'A', 'A', '0', 'grade', '0', '绩效等级', 1, to_date('13-03-2018 09:29:35', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 09:34:28', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (42, 'B', 'B', '1', 'grade', '0', '绩效等级', 1, to_date('13-03-2018 09:30:26', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 09:34:32', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (70, '实施', 'shishi', '1', 'pricetype', '0', '单价类型', 1, to_date('15-03-2018 10:21:59', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 10:21:59', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (75, '紧急', '紧急', '1', 'emergency', '0', '紧急程度', 1, to_date('15-03-2018 14:20:39', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 14:20:39', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (77, '项目立项', '项目立项', '0', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:47:37', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:47:37', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (79, '概念培训', '概念培训', '2', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:48:29', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:48:29', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (81, '数据收集', '数据收集', '4', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:49:11', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:49:11', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (83, '试运行', '试运行', '6', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:49:50', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:49:50', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (85, '项目验收', '项目验收', '8', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:50:28', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:50:28', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (86, '已开票', 'yikaipiao', '0', 'receiveNodeStatus', '0', '收款状态', 1, to_date('20-03-2018 14:23:21', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('20-03-2018 14:23:21', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (88, '已到账', 'yidaozhang', '2', 'receiveNodeStatus', '0', '已到账', 1, to_date('20-03-2018 14:24:29', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('20-03-2018 14:24:29', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (62, '中期', 'middle', '1', 'freeservicePeriod', '0', '免费服务期', 1, to_date('14-03-2018 16:56:20', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:56:20', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (23, '龙浩', 'longhao', '0', 'suppliername', '0', null, 1, to_date('12-03-2018 15:00:35', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('12-03-2018 15:00:35', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (44, '实施日报', '实施日报', '1', 'reportType', '0', '实施日报', 1, to_date('13-03-2018 16:13:31', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:13:31', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (65, '审批中', 'shenpi', '1', 'contractStatus', '0', '审批中', 1, to_date('15-03-2018 09:21:36', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 09:21:36', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (67, '已退回', 'yituihui', '3', 'contractStatus', '0', '已退回', 1, to_date('15-03-2018 09:24:48', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 09:24:48', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (69, '已立项', 'yilixiang', '5', 'contractStatus', '0', '已立项', 1, to_date('15-03-2018 09:28:28', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 09:28:28', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (71, '进行中', 'doing', '0', 'saleStatus', '0', '进行中', 1, to_date('15-03-2018 13:12:32', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 13:12:32', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (72, '招标中', 'zhaobiaozhong', '1', 'saleStatus', '0', '招标中', 1, to_date('15-03-2018 13:13:20', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 13:13:20', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (73, '已中标', 'yizhongbiao', '2', 'saleStatus', '0', '已中标', 1, to_date('15-03-2018 13:13:55', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 13:13:55', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (74, '一般', '一般', '0', 'emergency', '0', '紧急程度', 1, to_date('15-03-2018 14:20:15', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 14:20:42', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (76, 'admin', 'admin', '0', 'timerSender', '0', '月报定时器发送任务人员', 1, to_date('19-03-2018 09:45:10', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 09:45:10', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (92, '研发', '研发', '0', 'workHoursType', '0', '工时类型', 1, to_date('27-03-2018 15:07:32', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 15:07:32', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (93, '实施', '实施', '1', 'workHoursType', '0', '工时类型', 1, to_date('27-03-2018 15:07:51', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 15:07:51', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (94, '销售', '销售', '2', 'workHoursType', '0', '工时类型', 1, to_date('27-03-2018 15:08:12', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 15:08:12', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (45, '人民币', 'RMB', '0', 'currency', '0', null, 1, to_date('13-03-2018 16:22:39', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:22:39', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (46, '推广', 'AD', '0', 'activityType', '0', '销售活动推广', 1, to_date('13-03-2018 16:41:48', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:41:48', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (48, '调研', 'diaoyan', '2', 'activityType', '0', '销售活动-调研', 1, to_date('13-03-2018 16:44:07', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:44:07', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (50, 'FCS', 'FCS', '1', 'PRODUCT', '0', '产品-FCS', 1, to_date('13-03-2018 16:45:33', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:45:33', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (64, '编辑中', 'edit', '0', 'contractStatus', '0', '编辑中', 1, to_date('15-03-2018 09:20:27', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 09:20:27', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (66, '已审批', 'yishenpi', '2', 'contractStatus', '0', '已审批', 1, to_date('15-03-2018 09:23:26', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 09:23:26', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (68, '已删除', 'deleted', '4', 'contractStatus', '0', '已删除', 1, to_date('15-03-2018 09:27:41', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('15-03-2018 09:27:41', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (87, '已打款', 'yidakuan', '1', 'receiveNodeStatus', '0', '已打款', 1, to_date('20-03-2018 14:24:00', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('20-03-2018 14:24:00', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (90, '待审核', '待审核', '1', 'projectStatus', '0', '项目状态', 1, to_date('26-03-2018 13:26:48', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('29-03-2018 18:30:56', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (1, '男', 'man', '0', 'sex', '0', '性别', 1, to_date('02-03-2018 13:15:43', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:15:43', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (2, '女', 'woman', '1', 'sex', '0', '性别', 1, to_date('02-03-2018 13:15:43', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:15:43', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (3, '湖南', 'hunan', '0', 'place', '0', '籍贯', 1, to_date('02-03-2018 13:38:56', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:38:56', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (4, '安徽', 'anhui', '1', 'place', '0', '籍贯', 1, to_date('02-03-2018 13:38:56', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:38:56', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (5, '党员', 'party member', '0', 'face', '0', '政治面貌', 1, to_date('02-03-2018 13:40:11', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:40:11', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (6, '团员', 'woman', '1', 'face', '0', '政治面貌', 1, to_date('02-03-2018 13:40:11', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:40:11', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (7, '大专', 'college', '0', 'record', '0', '学历', 1, to_date('02-03-2018 13:44:41', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:44:41', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (8, '本科', 'Undergraduate course', '1', 'record', '0', '学历', 1, to_date('02-03-2018 13:44:41', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('02-03-2018 13:44:41', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (22, '外包', '外包', '1', 'userNature', '0', '外包', 1, to_date('12-03-2018 13:22:27', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('12-03-2018 13:22:27', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (53, '招标中', 'zhaobiao', '1', 'SALE_STATUS', '0', '招标中', 1, to_date('14-03-2018 14:12:35', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:54:44', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (55, '签约中', 'QIANYUE', '3', 'SALE_STATUS', '0', '签约中', 1, to_date('14-03-2018 14:13:43', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:54:23', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (57, '已取消', 'yiquxiao', '5', 'SALE_STATUS', '0', '已取消', 1, to_date('14-03-2018 14:16:04', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 14:16:04', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (61, '前期', 'first', '0', 'freeservicePeriod', '0', '免费服务期阶段', 1, to_date('14-03-2018 16:55:43', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:55:43', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (63, '后期', 'last', '2', 'freeservicePeriod', '0', '免费服务期', 1, to_date('14-03-2018 16:56:45', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:56:45', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (104, '未开始', '未开始', '0', 'milepostStatus', '0', '里程碑状态', 1, to_date('28-03-2018 17:28:47', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('28-03-2018 17:28:47', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (105, '进行中', '进行中', '1', 'milepostStatus', '0', '里程碑状态', 1, to_date('28-03-2018 17:29:07', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('28-03-2018 17:29:07', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (106, '已完成', '已完成', '2', 'milepostStatus', '0', '里程碑状态', 1, to_date('28-03-2018 17:29:26', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('28-03-2018 17:29:26', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (107, '已延误', '已延误', '3', 'milepostStatus', '0', '里程碑状态', 1, to_date('28-03-2018 17:29:51', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('28-03-2018 17:29:51', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (21, '合同员工', '合同员工', '0', 'userNature', '0', '合同员工', 1, to_date('12-03-2018 13:21:56', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('12-03-2018 13:21:56', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (24, '研发', 'yanfa', '0', 'pricetype', '0', null, 1, to_date('12-03-2018 15:04:38', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('12-03-2018 15:04:38', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (43, '研发日报', '研发日报', '0', 'reportType', '0', '研发日报', 1, to_date('13-03-2018 16:13:12', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:13:12', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (47, '招待', 'zhaodai', '1', 'activityType', '0', '销售活动-招待', 1, to_date('13-03-2018 16:43:15', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:43:15', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (49, 'SMS', 'SMS', '0', 'PRODUCT', '0', '产品-SMS', 1, to_date('13-03-2018 16:44:59', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:44:59', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (51, 'FOC', 'FOC', '2', 'PRODUCT', '0', '产品-FOC', 1, to_date('13-03-2018 16:45:56', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('13-03-2018 16:45:56', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (52, '进行中', 'doing', '0', 'SALE_STATUS', '0', '进行中', 1, to_date('14-03-2018 14:11:34', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:54:53', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (54, '已中标', 'haszhongbiao', '2', 'SALE_STATUS', '0', '已中标', 1, to_date('14-03-2018 14:13:11', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:54:35', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (56, '已签约', 'yiqianyue', '4', 'SALE_STATUS', '0', '已签约', 1, to_date('14-03-2018 14:15:15', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('14-03-2018 16:54:13', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (78, '启动会', '启动会', '1', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:48:08', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:48:08', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (80, '需求调研', '需求调研', '3', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:48:51', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:48:51', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (82, '项目开发', '项目开发', '5', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:49:28', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:49:28', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (84, '项目上线', '项目上线', '7', 'projectStage', '0', '项目阶段', 1, to_date('19-03-2018 18:50:08', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('19-03-2018 18:50:08', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (89, '编辑中', '编辑中', '0', 'projectStatus', '0', '项目状态', 1, to_date('26-03-2018 13:25:51', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('26-03-2018 13:25:51', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (91, '已立项', '已立项', '2', 'projectStatus', '0', '项目状态', 1, to_date('26-03-2018 13:27:23', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('29-03-2018 18:33:21', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (95, '差旅成本', '差旅成本', '0', 'costSports', '0', '费用大项', 1, to_date('27-03-2018 18:13:19', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:13:19', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (96, '其他成本', '其他成本', '1', 'costSports', '0', '费用大项', 1, to_date('27-03-2018 18:13:40', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:13:40', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (97, '交通费', '交通费', '0', 'costEventsTravel', '0', '费用小项-差旅', 1, to_date('27-03-2018 18:16:01', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:20:03', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (98, '住宿费', '住宿费', '1', 'costEventsTravel', '0', '费用小项-差旅', 1, to_date('27-03-2018 18:16:40', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:19:59', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (99, '出差补贴', '出差补贴', '2', 'costEventsTravel', '0', '费用小项-差旅', 1, to_date('27-03-2018 18:18:05', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:19:54', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (100, '招待费', '招待费', '0', 'costEventsOther', '0', '收费小项-其他', 1, to_date('27-03-2018 18:19:40', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:19:40', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (101, '房租费', '房租费', '1', 'costEventsOther', '0', '收费小项-其他', 1, to_date('27-03-2018 18:20:24', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:20:29', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (102, '是', 'YES', '0', 'yesOrNo', '0', '是否', 1, to_date('27-03-2018 18:42:12', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:42:12', 'dd-mm-yyyy hh24:mi:ss'));
insert into PMS_CODE (ID, CODE_ZH, CODE_EN, CODE_VALUE, CODE_TYPE, CODE_FLAG, CODE_REMARK, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
values (103, '否', 'NO', '1', 'yesOrNo', '0', '是否', 1, to_date('27-03-2018 18:42:26', 'dd-mm-yyyy hh24:mi:ss'), 1, to_date('27-03-2018 18:42:26', 'dd-mm-yyyy hh24:mi:ss'));
commit;


alter table pms_user add (user_Ip varchar2(100));
comment on column pms_user.user_Ip
  is '用户IP';
commit;

insert into pms_resource (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (181, 'R001_08', 'resourceManager/resourceManagerMain', '1', '资源管理', '资源管理', 1, 7, '0', 'fa-stack-overflow');

commit;

insert into pms_resource (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (182, 'OPERATION0101', null, '2', '操作权限', '操作权限', 181, 0, '0', null);

insert into pms_resource (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (183, 'R001_0801', null, '2', '资源移动', '资源移动', 182, 0, '0', null);

insert into pms_resource (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (184, 'R001_0802', null, '2', '禁用/启用资源', '禁用/启用资源', 182, 1, '0', null);

insert into pms_resource (ID, RESOURCE_CODE, RESOURCE_URL, RESOURCE_TYPE, RESOURCE_DESCCH, RESOURCE_DESCEN, RESOURCE_PID, RESOURCE_ORDER, RESOURCE_ISSHOW, RESOURCE_ICON)
values (185, 'R001_0803', null, '2', '新增/编辑资源', '新增/编辑资源', 182, 2, '0', null);

commit;

